# Generated by Django 2.2.5 on 2019-09-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('email', models.CharField(max_length=40, verbose_name='Email address')),
                ('mobile', models.CharField(max_length=30, verbose_name='Mobile number')),
                ('message', models.CharField(max_length=300, verbose_name='Message')),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip_address')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
